# Generated by Django 2.2.1 on 2019-07-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='PointTest',
        ),
    ]
