# Generated by Django 2.2.1 on 2019-07-12 12:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0003_auto_20190712_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milepointroute',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=26918),
        ),
    ]
