# Generated by Django 2.2.1 on 2019-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0004_auto_20190712_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milepointroute',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='milepointroute',
            name='edited_date',
            field=models.DateTimeField(null=True),
        ),
    ]
