# Generated by Django 2.2.1 on 2019-07-15 14:51

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0005_auto_20190712_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmDiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField()),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField()),
                ('meta', django.contrib.postgres.fields.hstore.HStoreField()),
                ('tainted', models.BooleanField()),
                ('type', models.IntegerField(choices=[(0, 'Way'), (1, 'Node'), (3, 'Relation'), (10, 'Undefined')], default=10)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
