# Generated by Django 2.2.1 on 2019-07-15 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0006_osmdiff'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmdiff',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
