# Generated by Django 2.2.1 on 2019-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0007_osmdiff_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmdiff',
            name='diff_id',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
