# Generated by Django 2.2.1 on 2019-07-15 17:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_sniffer', '0008_osmdiff_diff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OsmDiffBuffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff_id', models.IntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
